version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - "flask-app"
  flask-app:
    image: rwright1992/trio-app-jenkins:test
    build: ./flask-app
    depends_on:
    - "mysql"
  mysql:
    image: rwright1992/trio-db-jenkins:test
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}